added function to install vscode and vscodium using distrobox

diff --git a/configctl b/configctl
--- a/configctl
+++ b/configctl
@@ -290,3 +290,20 @@ function install_flatpak_apps() {
     re.sonny.Junction --user --assumeyes >> "$LOG" 2>&1 && echo "Finished." || echo "ERROR"
     
 }
+
+function install_vscode() {
+    echo -------------------
+    echo "Installing VSCode..."
+    echo -------------------
+    
+    distrobox create --image "$IMAGE_VSCODIUM_BASE"  --name code --home "$DISTROBOX_HOMES/Code" --init-hooks "microdnf install code -y" --yes >> "$LOG" 2>&1 && echo "Finished." || echo "ERROR"
+}
+
+    
+function install_vscodium() {
+    echo -------------------
+    echo "Installing VSCodium..."
+    echo -------------------
+    
+    distrobox create --image "$IMAGE_VSCODIUM_BASE" --name codium --home "$DISTROBOX_HOMES/Codium" --init-hooks "microdnf install codium -y" --yes >> "$LOG" 2>&1 && echo "Finished." || echo "ERROR"
+}
